-- ============================================================================
-- ONLINE FOOD ORDERING SYSTEM - DATABASE VIEWS
-- ============================================================================

-- 1. RESTAURANT SALES SUMMARY VIEW
-- Aggregates total revenue, total orders, completed vs cancelled counts per restaurant
DROP VIEW IF EXISTS v_restaurant_sales_summary;
CREATE VIEW v_restaurant_sales_summary AS
SELECT 
    r.restaurant_id,
    r.name AS restaurant_name,
    COUNT(o.order_id) AS total_orders_placed,
    SUM(CASE WHEN o.order_status = 'Delivered' THEN 1 ELSE 0 END) AS completed_orders,
    SUM(CASE WHEN o.order_status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_orders,
    COALESCE(SUM(CASE WHEN o.order_status = 'Delivered' THEN o.subtotal_amount ELSE 0 END), 0.00) AS net_subtotal_revenue,
    COALESCE(SUM(CASE WHEN o.order_status = 'Delivered' THEN o.total_amount ELSE 0 END), 0.00) AS gross_total_revenue,
    COALESCE(AVG(CASE WHEN o.order_status = 'Delivered' THEN o.total_amount ELSE NULL END), 0.00) AS avg_order_value
FROM restaurants r
LEFT JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.name;

-- 2. TOP RATED MENU ITEMS VIEW
-- Joins menu items with restaurant ratings and total order volume
DROP VIEW IF EXISTS v_top_rated_menu_items;
CREATE VIEW v_top_rated_menu_items AS
SELECT 
    mi.item_id,
    mi.name AS item_name,
    mi.price,
    mi.is_veg,
    r.restaurant_id,
    r.name AS restaurant_name,
    r.avg_rating AS restaurant_rating,
    mc.name AS category_name,
    COALESCE(SUM(oi.quantity), 0) AS total_quantity_sold
FROM menu_items mi
JOIN restaurants r ON mi.restaurant_id = r.restaurant_id
JOIN menu_categories mc ON mi.category_id = mc.category_id
LEFT JOIN order_items oi ON mi.item_id = oi.item_id
GROUP BY mi.item_id, mi.name, mi.price, mi.is_veg, r.restaurant_id, r.name, r.avg_rating, mc.name
ORDER BY total_quantity_sold DESC;

-- 3. BUSIEST HOURS ANALYSIS VIEW
-- Groups completed orders by hour of day
DROP VIEW IF EXISTS v_busiest_hours;
CREATE VIEW v_busiest_hours AS
SELECT 
    STRFTIME('%H', created_at) AS order_hour,
    COUNT(order_id) AS order_count,
    SUM(total_amount) AS hourly_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY STRFTIME('%H', created_at)
ORDER BY order_count DESC;

-- 4. POPULAR CUISINES VIEW
-- Calculates total orders and revenue generated by cuisine type
DROP VIEW IF EXISTS v_popular_cuisines;
CREATE VIEW v_popular_cuisines AS
SELECT 
    c.cuisine_id,
    c.name AS cuisine_name,
    COUNT(DISTINCT r.restaurant_id) AS restaurant_count,
    COUNT(o.order_id) AS total_orders,
    COALESCE(SUM(o.total_amount), 0.00) AS total_revenue
FROM cuisines c
JOIN restaurant_cuisines rc ON c.cuisine_id = rc.cuisine_id
JOIN restaurants r ON rc.restaurant_id = r.restaurant_id
LEFT JOIN orders o ON r.restaurant_id = o.restaurant_id AND o.order_status != 'Cancelled'
GROUP BY c.cuisine_id, c.name
ORDER BY total_orders DESC;
